name: "Runs E2E Tests"
description: "Runs E2E tests using chainsaw"
inputs:
  k8s-version:
    description: "Kubernetes version"
    required: false
  tests:
    description: "Test regex"
    required: true
  test-file:
    description: "Name of the chainsaw test file"
    default: chainsaw-test
runs:
  using: "composite"
  steps:
    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@82d8e747037f840e0ef9bdd97ecdc617f5535bdc # v0.2.8
    - name: Test with Chainsaw
      shell: bash
      run: |
        set -e

        K8S_VERSION="${{ inputs.k8s-version }}"
        TEST_FILE="${{ inputs.test-file }}"
        TESTS="${{ inputs.tests }}"

        if [[ "$TEST_FILE" == "chainsaw-test-vap" && -n "$K8S_VERSION" ]] && 
          [[ "$K8S_VERSION" == "v1.26."* || "$K8S_VERSION" == "v1.27."* ]]; then
          chainsaw test --config .chainsaw.yaml --include-test-regex '^chainsaw$/${{ inputs.tests }}' --test-file='${{ inputs.test-file }}' --no-color=false --selector='!skipForVapAlpha'
        else
          chainsaw test --config .chainsaw.yaml --include-test-regex '^chainsaw$/${{ inputs.tests }}' --test-file='${{ inputs.test-file }}' --no-color=false
        fi
