name: "Runs E2E Tests"
description: "Runs E2E tests using chainsaw"
inputs:
  tests:
    description: "Test regex"
    required: true
runs:
  using: "composite"
  steps:
    - name: Test with Chainsaw
      shell: bash
      run: |
        set -e
        chainsaw test --config .chainsaw.yaml --include-test-regex '^chainsaw$/${{ inputs.tests }}' --no-color=false
